import { createFileRoute } from "@tanstack/react-router";
import { Compass, Eye, HeartHandshake, Quote, ShieldCheck } from "lucide-react";
import aboutImage from "@/assets/about-team.jpg";
import chairmanImage from "@/assets/chairman-placeholder.jpg";
import { FinalCta, PageIntro, SectionHeader } from "@/components/sections";

export const Route = createFileRoute("/about")({ head: () => ({ meta: [
  { title: "About Us | Eastern Med Supplies" }, { name: "description", content: "Learn about Eastern Med Supplies, our mission, vision, values and commitment to healthcare supply." }, { property: "og:title", content: "About Eastern Med Supplies" }, { property: "og:description", content: "Our company approach, mission, vision and values." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }
], links: [{ rel: "canonical", href: "/about" }] }), component: AboutPage });

function AboutPage() { return <><PageIntro eyebrow="About us" title="Built around dependable healthcare support" text="A professional company profile designed for Eastern Med Supplies. Verified history, locations and operating details can be added when available." /><section className="section-pad"><div className="site-container grid items-center gap-14 lg:grid-cols-2"><img src={aboutImage} alt="Medical supply and healthcare professionals collaborating" width={1408} height={1008} loading="lazy" className="reveal aspect-[7/5] w-full object-cover" /><div className="reveal"><SectionHeader eyebrow="Our company" title="About Eastern Med Supplies" text="Eastern Med Supplies supports healthcare organisations with medical products and service-led supply solutions. This company introduction is intentionally general until the organisation’s verified founding story, geographic coverage and specialisations are provided." /><p className="mt-5 text-sm leading-7 text-muted-foreground">Our approach is grounded in understanding institutional needs, communicating clearly and helping clients identify appropriate product options.</p></div></div></section><section className="section-pad bg-muted"><div className="site-container grid gap-5 md:grid-cols-3">{[{ icon: Compass, title: "Mission", text: "To support healthcare delivery through responsive service and appropriate medical supply solutions." }, { icon: Eye, title: "Vision", text: "To be a valued medical supply partner known for professionalism and dependable relationships." }, { icon: ShieldCheck, title: "Core Values", text: "Integrity, responsibility, service, collaboration and a clear focus on healthcare needs." }].map(({ icon: Icon, title, text }) => <article key={title} className="icon-card reveal"><span className="icon-box"><Icon /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="section-pad"><div className="site-container grid overflow-hidden border border-border lg:grid-cols-[.7fr_1.3fr]"><img src={chairmanImage} alt="Leadership image placeholder" width={1008} height={1200} loading="lazy" className="h-full min-h-[27rem] w-full object-cover" /><div className="p-8 sm:p-12 lg:p-16"><Quote className="h-10 w-10 text-teal" /><p className="eyebrow mt-7">Leadership</p><h2 className="section-title">Message from the Chairman</h2><p className="mt-7 text-lg leading-8 text-muted-foreground">This is editable placeholder copy for the Chairman’s message. Replace it with the company’s authentic leadership perspective, commitment to customers and future direction.</p><div className="mt-9 flex items-center gap-3 border-t border-border pt-6"><HeartHandshake className="text-teal" /><div><p className="font-bold text-deep">Chairman Name — Placeholder</p><p className="text-sm text-muted-foreground">Chairman, Eastern Med Supplies</p></div></div></div></div></section><FinalCta /></> }
