import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Check, Mail } from "lucide-react";
import productCollection from "@/assets/product-collection.jpg";
import { getProduct } from "@/data/products";
import { Button } from "@/components/ui/button";
import { FinalCta } from "@/components/sections";

export const Route = createFileRoute("/products/")({
  loader: ({ params }) => { const product = getProduct(params.slug); if (!product) throw notFound(); return product; },
  head: ({ loaderData, params }) => ({ meta: [{ title: loaderData ? `${loaderData.name} | Eastern Med Supplies` : "Product Not Found | Eastern Med Supplies" }, { name: "description", content: loaderData?.description ?? "The requested product could not be found." }, { property: "og:title", content: loaderData?.name ?? "Product Not Found" }, { property: "og:description", content: loaderData?.description ?? "The requested product could not be found." }, { property: "og:type", content: "product" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: `/products/${params.slug}` }] }),
  component: ProductPage,
});
function ProductPage() { const product = Route.useLoaderData(); const subject = encodeURIComponent(`Product enquiry: ${product.name}`); return <><section className="section-pad bg-secondary"><div className="site-container"><Link to="/products" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="h-4 w-4" /> Back to products</Link><div className="grid gap-12 lg:grid-cols-2"><div className="overflow-hidden border border-border bg-background"><img src={productCollection} alt={`${product.name} catalogue placeholder`} width={1600} height={1008} className="aspect-[4/3] h-full w-full object-cover" style={{ objectPosition: product.imagePosition }} /></div><div><p className="eyebrow">{product.category}</p><h1 className="text-[clamp(2.5rem,5vw,4.5rem)] font-semibold leading-[1.05] text-deep">{product.name}</h1><p className="mt-6 text-base leading-8 text-muted-foreground">{product.description}</p><Button asChild variant="premium" size="lg" className="mt-8"><a href={`mailto:info@easternmedsupplies.com?subject=${subject}`}><Mail /> Enquire Now</a></Button><p className="mt-3 text-xs text-muted-foreground">Opens your email application.</p></div></div></div></section><section className="section-pad"><div className="site-container grid gap-10 lg:grid-cols-3">{[{ title: "Key Features", items: product.features }, { title: "Specifications", items: product.specifications }, { title: "Applications", items: product.applications }].map((group) => <article key={group.title} className="border-t-2 border-teal pt-6"><h2 className="text-xl font-bold text-deep">{group.title}</h2><ul className="mt-5 space-y-4">{group.items.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-muted-foreground"><Check className="mt-1 h-4 w-4 shrink-0 text-teal" />{item}</li>)}</ul></article>)}</div></section><FinalCta /></> }
